## python2.7实现
## 5.1便捷数据获取
数据的简单处理过程：1.数据收集；2.数据整理；3.数据描述；4.数据分析

In [5]:
#便捷网络数据： 调用对应的库来实现
from matplotlib.finance import quotes_historical_yahoo_ochl
#这个包可以直接获取Yahoo财经上面的数据
#matplotlib.finance.quotes_historical_yahoo_ochl(ticker, date1, date2, asobject=False, adjusted=True, cachename=None)
#http://matplotlib.org/api/finance_api.html
from datetime import date
import pandas as pd
today = date.today()
start = (today.year-1,today.month,today.day)
#去年的今天到今年的今天
quotes = quotes_historical_yahoo_ochl('AXP',start,today)
#AXP是公司股票代号
df = pd.DataFrame(quotes)
#print df
##行代表意思： 0：日期；1：开票价；2：收盘价；3：最高价；4：最低价；5：成交量

#给上面获取的数据每列加上对应的属性columns = fields
#让index的值从1开始index = range(1,len(quotes)+1)
fields = ['date','open','close','high','low','volume']
quotesdf = pd.DataFrame(quotes, index = range(1,len(quotes)+1),columns = fields)
print quotesdf

         date       open      close       high        low      volume
1    735971.0  62.964130  62.424551  63.189777  62.365687  10003600.0
2    735974.0  62.532468  62.836596  62.993561  61.904589   8157100.0
3    735975.0  63.572387  63.179964  63.670492  62.395116   7560000.0
4    735976.0  62.444173  61.659325  63.150534  61.051073  11291200.0
5    735977.0  61.659325  62.090992  62.542276  61.188419   6664000.0
6    735978.0  60.854860  61.718190  61.855537  60.334902   8597300.0
7    735982.0  62.208719  61.453305  62.581521  61.060886   7652100.0
8    735983.0  60.374146  61.835916  62.336256  60.128882   9043800.0
9    735984.0  61.806486  61.453305  63.101479  61.325767   8992300.0
10   735985.0  57.283819  54.016907  57.774347  53.114334  43783400.0
11   735988.0  53.428272  53.977664  54.713455  53.114334  18498300.0
12   735989.0  54.154255  54.046338  54.684026  53.918800  12844800.0
13   735990.0  54.321032  53.487136  54.762508  53.389029  11044100.0
14   735991.0  53.644105  51.878206  53.722587  51.162037  18015000.0
15   735992.0  52.172522  52.486460  52.692481  52.044984  13981100.0
16   735995.0  52.398165  53.663727  53.948234  51.995932   9861900.0
17   735996.0  53.300737  52.643428  53.359597  52.476651  11698400.0
18   735997.0  52.976987  53.084904  53.261494  51.829154   9729800.0
19   735998.0  53.055473  53.349789  53.428271  52.790587   6904000.0
20   735999.0  53.683348  52.957366  53.810882  52.790588   9159600.0
21   736002.0  52.231386  51.407300  52.437407  51.240519  11830600.0
22   736003.0  51.269950  51.632943  52.015554  50.926582   8588900.0
23   736004.0  51.995932  51.299384  52.417786  51.289571   7081900.0
24   736005.0  50.249654  50.141738  50.612644  49.317651   9214500.0
25   736006.0  50.897151  51.662373  51.731047  50.661696   6107700.0
26   736010.0  52.005741  52.172522  52.466839  51.731047   7163800.0
27   736011.0  52.486459  52.594376  52.976987  52.290247   8638900.0
28   736012.0  52.486459  53.124147  53.320354  52.437407   8502900.0
29   736013.0  53.222252  53.673536  53.987474  53.006418   6557000.0
30   736016.0  53.673535  54.576108  54.576108  53.673535   6537800.0
..        ...        ...        ...        ...        ...         ...
223  736291.0  71.634485  72.570488  72.610319  71.206311   4661400.0
224  736293.0  72.660110  72.550577  72.869217  72.152274   1900400.0
225  736296.0  72.221976  71.823673  72.460955  71.664356   4467700.0
226  736297.0  71.893376  71.186392  71.953126  71.086818   3814800.0
227  736298.0  71.694228  71.734059  72.022828  71.475161   4812500.0
228  736299.0  72.142314  72.221976  72.460955  71.475161   4298200.0
229  736300.0  72.212016  71.554823  72.351429  71.126648   2959100.0
230  736303.0  72.022829  71.724100  72.331509  71.684269   3929100.0
231  736304.0  72.162232  72.002909  72.431083  71.773890   3843900.0
232  736305.0  72.162233  73.974504  74.402678  71.923254   5801500.0
233  736306.0  74.482340  74.591874  74.880635  73.675775   3415800.0
234  736307.0  74.522163  74.452461  74.591873  73.974503   2566900.0
235  736310.0  74.382759  73.267520  74.382759  72.839346   3654900.0
236  736311.0  73.357134  73.526410  73.914761  72.799515   2892900.0
237  736312.0  73.217729  73.755437  75.408390  72.928960   5415800.0
238  736313.0  74.223443  74.621745  75.418344  74.024287   4061600.0
239  736314.0  74.970257  74.681488  75.059871  74.263274   8200600.0
240  736317.0  74.362847  74.233402  74.810933  73.825139   3076600.0
241  736318.0  74.681487  74.741230  75.179363  74.213482   3244900.0
242  736319.0  74.791021  75.000128  75.249066  74.372806   3244500.0
243  736320.0  74.681487  74.263273  75.049919  74.183611   2865200.0
244  736321.0  74.422590  74.651616  74.920466  74.422590   1957500.0
245  736325.0  74.781061  74.661576  74.791022  74.472381   2049400.0
246  736326.0  74.711359  74.054166  75.059871  73.835099   2517300.0
247  736327.0  73.954585  73.606072  74.362846  73.187858   2573700.0
248  736328.0  73.645904  73.765397  74.024287  73.526410   3378800.0
249  736332.0  74.571955  75.030000  75.428303  74.422591   5853900.0
250  736333.0  75.260002  76.260002  76.550003  75.059998   4635800.0
251  736334.0  76.000000  75.320000  76.180000  74.820000   3383000.0
252  736335.0  75.400002  75.470001  75.919998  75.059998   3061400.0

[252 rows x 6 columns]

In [6]:
#日期转换方法，这种735971日期表示是西方的某一种日历
firstday = date.fromordinal(735971)
lastday = date.fromordinal(736335)
print firstday
print lastday

2016-01-08
2017-01-06

In [11]:
#完整的程序
from matplotlib.finance import quotes_historical_yahoo_ochl
from datetime import date
from datetime import datetime
import pandas as pd
today = date.today()
start = (today.year-1, today.month, today.day)
quotes = quotes_historical_yahoo_ochl('AXP', start, today)
fields = ['date','open','close','high','low','volume']
list1 = []
for i in range(0,len(quotes)):
    x = date.fromordinal(int(quotes[i][0]))
    #把日期转换成常规格式
    y = datetime.strftime(x,'%Y-%m-%d')
    #转换成固定格式，%Y表示年完整显示，%y只显示后两位
    list1.append(y)
    #增加日期列表的长度
quotesdf = pd.DataFrame(quotes, index = list1, columns = fields)
quotesdf = quotesdf.drop(['date'], axis = 1)
#删除原来date列
print quotesdf

                 open      close       high        low      volume
2016-01-08  62.964130  62.424551  63.189777  62.365687  10003600.0
2016-01-11  62.532468  62.836596  62.993561  61.904589   8157100.0
2016-01-12  63.572387  63.179964  63.670492  62.395116   7560000.0
2016-01-13  62.444173  61.659325  63.150534  61.051073  11291200.0
2016-01-14  61.659325  62.090992  62.542276  61.188419   6664000.0
2016-01-15  60.854860  61.718190  61.855537  60.334902   8597300.0
2016-01-19  62.208719  61.453305  62.581521  61.060886   7652100.0
2016-01-20  60.374146  61.835916  62.336256  60.128882   9043800.0
2016-01-21  61.806486  61.453305  63.101479  61.325767   8992300.0
2016-01-22  57.283819  54.016907  57.774347  53.114334  43783400.0
2016-01-25  53.428272  53.977664  54.713455  53.114334  18498300.0
2016-01-26  54.154255  54.046338  54.684026  53.918800  12844800.0
2016-01-27  54.321032  53.487136  54.762508  53.389029  11044100.0
2016-01-28  53.644105  51.878206  53.722587  51.162037  18015000.0
2016-01-29  52.172522  52.486460  52.692481  52.044984  13981100.0
2016-02-01  52.398165  53.663727  53.948234  51.995932   9861900.0
2016-02-02  53.300737  52.643428  53.359597  52.476651  11698400.0
2016-02-03  52.976987  53.084904  53.261494  51.829154   9729800.0
2016-02-04  53.055473  53.349789  53.428271  52.790587   6904000.0
2016-02-05  53.683348  52.957366  53.810882  52.790588   9159600.0
2016-02-08  52.231386  51.407300  52.437407  51.240519  11830600.0
2016-02-09  51.269950  51.632943  52.015554  50.926582   8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571   7081900.0
2016-02-11  50.249654  50.141738  50.612644  49.317651   9214500.0
2016-02-12  50.897151  51.662373  51.731047  50.661696   6107700.0
2016-02-16  52.005741  52.172522  52.466839  51.731047   7163800.0
2016-02-17  52.486459  52.594376  52.976987  52.290247   8638900.0
2016-02-18  52.486459  53.124147  53.320354  52.437407   8502900.0
2016-02-19  53.222252  53.673536  53.987474  53.006418   6557000.0
2016-02-22  53.673535  54.576108  54.576108  53.673535   6537800.0
...               ...        ...        ...        ...         ...
2016-11-23  71.634485  72.570488  72.610319  71.206311   4661400.0
2016-11-25  72.660110  72.550577  72.869217  72.152274   1900400.0
2016-11-28  72.221976  71.823673  72.460955  71.664356   4467700.0
2016-11-29  71.893376  71.186392  71.953126  71.086818   3814800.0
2016-11-30  71.694228  71.734059  72.022828  71.475161   4812500.0
2016-12-01  72.142314  72.221976  72.460955  71.475161   4298200.0
2016-12-02  72.212016  71.554823  72.351429  71.126648   2959100.0
2016-12-05  72.022829  71.724100  72.331509  71.684269   3929100.0
2016-12-06  72.162232  72.002909  72.431083  71.773890   3843900.0
2016-12-07  72.162233  73.974504  74.402678  71.923254   5801500.0
2016-12-08  74.482340  74.591874  74.880635  73.675775   3415800.0
2016-12-09  74.522163  74.452461  74.591873  73.974503   2566900.0
2016-12-12  74.382759  73.267520  74.382759  72.839346   3654900.0
2016-12-13  73.357134  73.526410  73.914761  72.799515   2892900.0
2016-12-14  73.217729  73.755437  75.408390  72.928960   5415800.0
2016-12-15  74.223443  74.621745  75.418344  74.024287   4061600.0
2016-12-16  74.970257  74.681488  75.059871  74.263274   8200600.0
2016-12-19  74.362847  74.233402  74.810933  73.825139   3076600.0
2016-12-20  74.681487  74.741230  75.179363  74.213482   3244900.0
2016-12-21  74.791021  75.000128  75.249066  74.372806   3244500.0
2016-12-22  74.681487  74.263273  75.049919  74.183611   2865200.0
2016-12-23  74.422590  74.651616  74.920466  74.422590   1957500.0
2016-12-27  74.781061  74.661576  74.791022  74.472381   2049400.0
2016-12-28  74.711359  74.054166  75.059871  73.835099   2517300.0
2016-12-29  73.954585  73.606072  74.362846  73.187858   2573700.0
2016-12-30  73.645904  73.765397  74.024287  73.526410   3378800.0
2017-01-03  74.571955  75.030000  75.428303  74.422591   5853900.0
2017-01-04  75.260002  76.260002  76.550003  75.059998   4635800.0
2017-01-05  76.000000  75.320000  76.180000  74.820000   3383000.0
2017-01-06  75.400002  75.470001  75.919998  75.059998   3061400.0

[252 rows x 5 columns]

In [12]:
#创建时间序列
import pandas as pd
dates1 = pd.date_range('20141001', periods=7)
print dates1
print '**************'
import numpy as np
dates2 = pd.DataFrame(np.random.randn(7,3),index=dates1,columns = list('ABC'))
print dates2

DatetimeIndex(['2014-10-01', '2014-10-02', '2014-10-03', '2014-10-04',
               '2014-10-05', '2014-10-06', '2014-10-07'],
              dtype='datetime64[ns]', freq='D')
**************
                   A         B         C
2014-10-01  0.289667  0.734712  0.175514
2014-10-02  1.320951 -0.477086  1.650003
2014-10-03 -0.954368 -0.199560 -1.540550
2014-10-04 -0.486956 -0.755750  0.995522
2014-10-05 -1.139133  1.131752  0.338929
2014-10-06 -0.415307 -0.423968 -0.360899
2014-10-07  0.579088 -0.675231 -0.485676

### 5.3数据显示
* 显示方式：显示索引(df.index)；显示列名(df.columns)；显示数据的值(df.values)；显示数据描述(df.describe) 
* 显示行：专用方式；切片
  df.head(n):显示从头开始的索引前n个数； df.tail(n):显示从尾开始的索引倒数n个数

In [23]:
print quotesdf.index[:5]
print quotesdf.columns
print quotesdf.values[-1:-3:-1]
#print quotesdf.describe
print quotesdf.head(2)
print '**************'
print quotesdf.tail(3)

Index([u'2016-01-08', u'2016-01-11', u'2016-01-12', u'2016-01-13',
       u'2016-01-14'],
      dtype='object')
Index([u'open', u'close', u'high', u'low', u'volume'], dtype='object')
[[  7.54000020e+01   7.54700010e+01   7.59199980e+01   7.50599980e+01
    3.06140000e+06]
 [  7.60000000e+01   7.53200000e+01   7.61800000e+01   7.48200000e+01
    3.38300000e+06]]
                 open      close       high        low      volume
2016-01-08  62.964130  62.424551  63.189777  62.365687  10003600.0
2016-01-11  62.532468  62.836596  62.993561  61.904589   8157100.0
**************
                 open      close       high        low     volume
2017-01-04  75.260002  76.260002  76.550003  75.059998  4635800.0
2017-01-05  76.000000  75.320000  76.180000  74.820000  3383000.0
2017-01-06  75.400002  75.470001  75.919998  75.059998  3061400.0

### 5.4数据选择
* 选择方式：
 选择行:切片；索引  
 选择列：列名；行、列（标签label（loc））   
 行和列的区域：标签label（loc）；iloc（位置）   
 单个值：at；iat(索引必须是整数)   
 注意loc,iloc,at,iat,ix用法的区别，具体百度pandas 。。。。   
 条件筛选

In [12]:
print quotesdf[u'2016-02-08 ':u'2016-02-10 ']
#直接根据索引值来索引相关内容，索引方式直接
#u表示Unicode，如果缺少了就无法找到
print quotesdf['open'][1:3]
print quotesdf.close[2:4]
#根据列名选择,会打印出索引值
print quotesdf.loc[u'2016-02-08 ':u'2016-02-10 ',]
#df.loc[rows,columns] 根据行标签和列标签进行选择，row,columns参数是可以选择的
print quotesdf.loc[u'2016-02-08 ':u'2016-02-10 ',['open','high']]
#print quotesdf.iloc[u'2016-02-08 ':u'2016-02-10 ',['open','high']]
#TypeError: cannot perform reduce with flexible type
#选择块区域
#print quotesdf.loc[:,['open','high']]
#  ":"不能缺

#选择单个值
print quotesdf.loc[u'2016-02-08','open']
print quotesdf.at[u'2016-02-08','open']
#print quotesdf.iat[u'2016-02-08','open']
#ValueError: iAt based indexing can only have integer indexers

#条件选择
print quotesdf[quotesdf.index>=u'2017-01-05']
print quotesdf[(quotesdf.index>=u'2016-08-05')&(quotesdf.close>=75)]

                 open      close       high        low     volume
2016-02-09  51.269950  51.632943  52.015554  50.926582  8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571  7081900.0
2016-01-11    62.532468
2016-01-12    63.572387
Name: open, dtype: float64
2016-01-12    63.179964
2016-01-13    61.659325
Name: close, dtype: float64
                 open      close       high        low     volume
2016-02-09  51.269950  51.632943  52.015554  50.926582  8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571  7081900.0
                 open       high
2016-02-09  51.269950  52.015554
2016-02-10  51.995932  52.417786
52.2313864571
52.2313864571
                 open      close       high        low     volume
2017-01-05  76.000000  75.320000  76.180000  74.820000  3383000.0
2017-01-06  75.400002  75.470001  75.919998  75.059998  3061400.0
                 open      close       high        low     volume
2016-12-21  74.791021  75.000128  75.249066  74.372806  3244500.0
2017-01-03  74.571955  75.030000  75.428303  74.422591  5853900.0
2017-01-04  75.260002  76.260002  76.550003  75.059998  4635800.0
2017-01-05  76.000000  75.320000  76.180000  74.820000  3383000.0
2017-01-06  75.400002  75.470001  75.919998  75.059998  3061400.0

### 5.5简单统计与筛选

In [74]:
#求开盘价的平均值 
#print quotesdf.mean(columns = 'open')
#TypeError: mean() got an unexpected keyword argument 'columns'

#收盘价高于开盘价的天数
print len(quotesdf[quotesdf.close > quotesdf.open])
print len(quotesdf)-len(quotesdf[quotesdf.close > quotesdf.open])

#统计相邻两天收盘价的涨跌情况
status = np.sign(np.diff(quotesdf.close))
print status
print status[np.where( status == 1.)].size
#1 表示涨
print status[np.where( status == -1.)].size
# -1表示跌

#排序  sort函数有很多问题？？？
print quotesdf.sort(columns='open')[:10]
#前10天开盘价排序,默认是升序排列
#DataFrame的sort()函数已不推荐使用，相同功能推荐使用sort_index()函数
#re_quotesdf_sort = quotesdf['open'][:10]
#print re_quotesdf_sort.sort(ascending = False)
#可以添加sort()函数的ascending属性控制顺序/逆序排序，默认该属性=True，即顺序排列
#TypeError: sort() got an unexpected keyword argument 'reverse'
#print quotesdf.sort(columns='open')[:10].close

134
118
[ 1.  1. -1.  1. -1. -1.  1. -1. -1. -1.  1. -1. -1.  1.  1. -1.  1.  1.
 -1. -1.  1. -1. -1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1.  1.
  1.  1.  1.  1. -1. -1.  1.  1. -1.  1.  1.  1. -1. -1.  1. -1. -1.  1.
 -1.  1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1. -1.  1.  1.  1.  1.  1.
 -1.  1.  1. -1. -1.  1. -1. -1. -1.  1. -1.  1. -1. -1. -1. -1. -1.  1.
 -1.  1. -1.  1.  1. -1.  1.  1.  1.  1. -1.  1. -1.  1. -1. -1. -1. -1.
  1.  1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1.  1.
  1.  1. -1. -1.  1. -1.  1. -1.  1. -1. -1. -1.  1. -1. -1. -1.  1. -1.
  1. -1.  1.  1.  1.  1. -1.  1. -1. -1.  1. -1.  1. -1.  1.  1. -1. -1.
  1. -1. -1.  1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.  1.  1.  1.
  1. -1. -1.  1.  1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.
 -1.  1. -1.  1.  1.  1. -1. -1. -1.  1.  1. -1.  1.  1.  1.  1. -1. -1.
  1.  1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1.  1.  1.  1. -1.  1.]
140
111
                 open      close       high        low      volume
2016-02-11  50.249654  50.141738  50.612644  49.317651   9214500.0
2016-02-12  50.897151  51.662373  51.731047  50.661696   6107700.0
2016-02-09  51.269950  51.632943  52.015554  50.926582   8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571   7081900.0
2016-02-16  52.005741  52.172522  52.466839  51.731047   7163800.0
2016-01-29  52.172522  52.486460  52.692481  52.044984  13981100.0
2016-02-08  52.231386  51.407300  52.437407  51.240519  11830600.0
2016-02-01  52.398165  53.663727  53.948234  51.995932   9861900.0
2016-02-17  52.486459  52.594376  52.976987  52.290247   8638900.0
2016-02-18  52.486459  53.124147  53.320354  52.437407   8502900.0

d:\python27\lib\site-packages\ipykernel\__main__.py:18: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [15]:
#计数统计
#统计2016年2月份开盘天数
t = quotesdf[(quotesdf.index >= u'2016-02-01') & (quotesdf.index < u'2016-03-01')]
print len(t)

#统计近一年每个月的股票开盘天数
import time
listtemp = []
for i in range(0,len(quotesdf)):
    temp = time.strptime(quotesdf.index[i],"%Y-%m-%d")
    listtemp.append(temp.tm_mon)
print listtemp
tempdf = quotesdf.copy()
tempdf['month'] = listtemp
print tempdf['month'].value_counts()
#.value_counts()每个月的天数相加

20
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1, 1, 1, 1]
8     23
6     22
3     22
12    21
11    21
10    21
9     21
5     21
4     21
7     20
2     20
1     19
Name: month, dtype: int64

### 5.6分组

In [84]:
#统计近一年每个月的股票开盘天数？
print tempdf.groupby('month').count()
#天数
#print tempdf.groupby('month').count().month
#AttributeError: 'DataFrame' object has no attribute 'month'
print tempdf.groupby('month').count().open

#如果更高效统计近一年每个月的总成交量？
print tempdf.groupby('month').sum().volume

#更高效的统计近一年每个月的总成交量，对于大量数据计数效率就会比较前一个高
g = tempdf.groupby('month')
gvolume = g['volume']
print gvolume.sum()

       open  close  high  low  volume
month
1        19     19    19   19      19
2        20     20    20   20      20
3        22     22    22   22      22
4        21     21    21   21      21
5        21     21    21   21      21
6        22     22    22   22      22
7        20     20    20   20      20
8        23     23    23   23      23
9        21     21    21   21      21
10       21     21    21   21      21
11       21     21    21   21      21
12       21     21    21   21      21
month
1     19
2     20
3     22
4     21
5     21
6     22
7     20
8     23
9     21
10    21
11    21
12    21
Name: open, dtype: int64
month
1     213062200.0
2     159711400.0
3     129864200.0
4      99855500.0
5      96741700.0
6     121788800.0
7      90064900.0
8      77514100.0
9      95572800.0
10    116243400.0
11     99527200.0
12     75948200.0
Name: volume, dtype: float64
month
1     213062200.0
2     159711400.0
3     129864200.0
4      99855500.0
5      96741700.0
6     121788800.0
7      90064900.0
8      77514100.0
9      95572800.0
10    116243400.0
11     99527200.0
12     75948200.0
Name: volume, dtype: float64

### 5.7合并
* Append： 加行到DataFrame
* Concat：连接pandas对象
* Join： SQL类型的连接

In [13]:
#把美国运通公司股票2016-02-08至2016-02-10的交易信息合并到近一年中前两天的股票信息中？
p = quotesdf[:2]
print p
q = quotesdf[u'2016-02-08 ':u'2016-02-10 ']
#索引值一定要存在，如果给定的头尾值不存在索引结果就为空，因为这里的日期不是连续的
print q
print p.append(q)

                 open      close       high        low      volume
2016-01-08  62.964130  62.424551  63.189777  62.365687  10003600.0
2016-01-11  62.532468  62.836596  62.993561  61.904589   8157100.0
                 open      close       high        low     volume
2016-02-09  51.269950  51.632943  52.015554  50.926582  8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571  7081900.0
                 open      close       high        low      volume
2016-01-08  62.964130  62.424551  63.189777  62.365687  10003600.0
2016-01-11  62.532468  62.836596  62.993561  61.904589   8157100.0
2016-02-09  51.269950  51.632943  52.015554  50.926582   8588900.0
2016-02-10  51.995932  51.299384  52.417786  51.289571   7081900.0

In [17]:
pieces = [tempdf[:5], tempdf[len(tempdf)-5:]]
print pd.concat(pieces)

#不同逻辑结构的对象可以相互连接
piece1 = quotesdf[:3]
piece2 = tempdf[:3]
print pd.concat([piece1,piece2],ignore_index = True)
#ignore_index = True

                 open      close       high        low      volume  month
2016-01-08  62.964130  62.424551  63.189777  62.365687  10003600.0      1
2016-01-11  62.532468  62.836596  62.993561  61.904589   8157100.0      1
2016-01-12  63.572387  63.179964  63.670492  62.395116   7560000.0      1
2016-01-13  62.444173  61.659325  63.150534  61.051073  11291200.0      1
2016-01-14  61.659325  62.090992  62.542276  61.188419   6664000.0      1
2016-12-30  73.645904  73.765397  74.024287  73.526410   3378800.0     12
2017-01-03  74.571955  75.030000  75.428303  74.422591   5853900.0      1
2017-01-04  75.260002  76.260002  76.550003  75.059998   4635800.0      1
2017-01-05  76.000000  75.320000  76.180000  74.820000   3383000.0      1
2017-01-06  75.400002  75.470001  75.919998  75.059998   3061400.0      1
       close       high        low  month       open      volume
0  62.424551  63.189777  62.365687    NaN  62.964130  10003600.0
1  62.836596  62.993561  61.904589    NaN  62.532468   8157100.0
2  63.179964  63.670492  62.395116    NaN  63.572387   7560000.0
3  62.424551  63.189777  62.365687    1.0  62.964130  10003600.0
4  62.836596  62.993561  61.904589    1.0  62.532468   8157100.0
5  63.179964  63.670492  62.395116    1.0  63.572387   7560000.0

### merge
left  right  how on left_on right_on left_index right_index sort suffixes copy